
-- ----------------------------
--  Table structure for `Competition`
-- ----------------------------
-- DROP TABLE IF EXISTS Competition;
CREATE TABLE Competition (
  CompetitionId smallint PRIMARY KEY,
  CompetitionDate date not null,
  Name varchar(30) not null );

-- ----------------------------
--  Table structure for `CompetitionPart`
-- ----------------------------
DROP TABLE IF EXISTS CompetitionPart;
CREATE TABLE CompetitionPart (
  CompetitionPartId smallint primary key,
  Name varchar(30) not null,
  Length decimal(5,2) ,
  CompetitionId smallint,
  Type varchar(12) ,
  Time decimal(5,2) 
);

ALTER TABLE CompetitionPart
    ADD CONSTRAINT fk_PerCompetition
    FOREIGN KEY (CompetitionId)
    REFERENCES Competition(CompetitionId);

-- ----------------------------
--  Table structure for `Reader`
-- ----------------------------
DROP TABLE IF EXISTS Reader;
CREATE TABLE Reader (
  ReaderId smallint ,
  Lap smallint not null,
  CompetitionPartId smallint not null,
  ReaderType varchar(10) ,
  LengthFromStart decimal(5,2),
  primary key(ReaderId, Lap, CompetitionPartId, ReaderType)
);

ALTER TABLE Reader
    ADD CONSTRAINT fk_PerCompetitionPart
    FOREIGN KEY (CompetitionPartId)
    REFERENCES CompetitionPart(CompetitionPartId);
commit;


-- ----------------------------
--  Table structure for `ReaderRegistration`
-- ----------------------------
DROP TABLE IF EXISTS ReaderConfiguration;
CREATE TABLE ReaderConfiguration (
  ReaderId smallint PRIMARY KEY,
  IPAdress varchar(20),
  Readpower smallint,
  AsyncOffTime smallint
);
commit;

-- ----------------------------
--  Table structure for `ReaderRegistration`
-- ----------------------------
DROP TABLE IF EXISTS ReaderRegistration;
CREATE TABLE ReaderRegistration (
  Id int GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1, INCREMENT BY 1) NOT NULL ,
  ReaderId smallint,
  RFID varchar(30),
  AntennId smallint,
  ReaderDateTime date,
  AppDateTime date,
  TimeStamp timeStamp,  
  ReaderCount smallint,
  PRIMARY KEY (Id)
);
commit;

ALTER TABLE ReaderRegistration
    ADD CONSTRAINT fk_PerReaderConfiguration
    FOREIGN KEY (ReaderId)
    REFERENCES ReaderConfiguration(ReaderId);
commit;

-- ----------------------------
--  Table structure for `StartingGroup`
-- ----------------------------
DROP TABLE IF EXISTS StartingGroup;
CREATE TABLE StartingGroup (
  Id smallint primary key,
  CompetitionPartId smallint not null,
  StartArea varchar(30) not null,
  AutomaticStart smallint not null ,
  OfficialStartTime timeStamp,
  ActualStartTime timeStamp 
);

ALTER TABLE StartingGroup
    ADD CONSTRAINT fk_StartingGroupPerCompetitionPart
    FOREIGN KEY (CompetitionPartId)
    REFERENCES CompetitionPart(CompetitionPartId);


-- ----------------------------
--  Table structure for `StartId`
-- ----------------------------
DROP TABLE IF EXISTS StartId;
CREATE TABLE StartId (
  StartNr smallint primary key,
  CompetitionPartId smallint,
  RFID varchar(30), 
  StartingGroupId smallint
);

ALTER TABLE StartId
    ADD CONSTRAINT fk_StartIdPerCompetitionPart
    FOREIGN KEY (CompetitionPartId)
    REFERENCES CompetitionPart(CompetitionPartId);

ALTER TABLE StartId
    ADD CONSTRAINT fk_StartIdPerStartingGroup
    FOREIGN KEY (StartingGroupId)
    REFERENCES StartingGroup(Id);